### PR TITLE
Display empty lines instead of 0 for missing values in timeseries

### LINKED ISSUE #1706: Render missing timeseres data differently than zeroed
We currently handle missing timeseries data by giving it a value of zero and rendering it as a such.  We should allow for the missing data to be rendered  in some distinguishing fashion.

### PR DESCRIPTION
**Pull request by YohannParis**
closes #1706 

Change backend to send `null` value instead of `0` if data is missing.
Added a **void** sparkline to illustrate the missing data. The strokes are so thin than using a gradient will be indistinguishable from real data.

### Sparkline
**Before** and **After**
Screen Shot 2020-07-30 at 16 07 56

### Line Chart
**Before**
Screen Shot 2020-07-30 at 16 20 19

 **After**
Screen Shot 2020-07-30 at 16 18 52

### CODE REVIEW

**Comment by YohannParis** [comment]
I fill like we are not able to see as well values that are alone from a pack (the spike in the before images).

**Comment by cdbethune** [comment]
Yeah, I think if want to go this way then we need to thicken the stroke up and / or use a higher contrast colour.  Maybe I can flip a screen shot to Pascale and see what she thinks.

**Comment by cdbethune** [comment]
Pascale's suggestion:

image

**Comment by YohannParis** [comment]
Yep that's I thought.
This one is going to be fun :)

**Comment by YohannParis** [comment]
Updated with new scoring display:
Screen Shot 2020-07-31 at 14 44 41

Screen Shot 2020-07-31 at 14 44 33

**Pull request merged**
